### PR TITLE
Set transparency level

### PR DESCRIPTION
**Pull request by sebastiant**
Add defined transparency level with default value of 4%

### CODE REVIEW

**Comment by coolwanglu** [comment]
Why should we include this in a color scheme?

**Comment by sebastiant** [comment]
That was a rhetorical question, yes?

**Comment by coolwanglu** [comment]
@sebastiant Um, I mean, this color scheme should follow the original solarized scheme, if there's any spec about transparent level of the background, we should set the same value.

**Comment by sebastiant** [comment]
yes, you're right. Sort of saw this project as something other than it really is. What you're saying makes sense, i'll just keep my fork for my (purely convenient) needs

**Pull request closed without merging**
